# Generated by Django 4.1 on 2022-09-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reg', '0004_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='room',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
