# Generated by Django 4.1 on 2022-09-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reg', '0005_date_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='date',
            name='start_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
