# Generated by Django 4.1.1 on 2022-09-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reg', '0009_alter_enrollment_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
