# Generated by Django 4.1.1 on 2022-09-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reg', '0010_delete_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_reg.date')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_reg.student')),
            ],
        ),
    ]
