# Generated by Django 4.1.1 on 2022-09-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reg', '0012_alter_student_course_enroll_delete_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seat',
        ),
        migrations.AddField(
            model_name='date',
            name='seat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
