# Generated by Django 4.1.1 on 2022-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reg', '0013_remove_course_seat_date_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
