# Generated by Django 4.1.1 on 2022-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reg', '0014_date_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='semester',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='year',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
